
name: dump context

on:
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          env | sort
      - uses: jcii/jcii-dump-context-action@0.1.5
        with:
          milliseconds: 1000
          blahblah_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          env | grep INPUT 