
name: dump context

on:
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - runs: |
          env
      - uses: jcii/jcii-dump-context-action@0.1.1
        with:
          milliseconds: 1000